// Fetches the league's public Google Sheet ("2026/2" tab) and regenerates
// src/data/matches.generated.ts. Run by .github/workflows/refresh-fixtures.yml,
// or manually with: node scripts/refresh-fixtures.ts
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { teams, SEASON } from "../src/data/league.ts";
import { parseCsv, parseFixtureRows } from "../src/data/fixture-parser.ts";
import type { DivisionId } from "../src/data/types.ts";

const SHEET_ID = "1xD2Yc5dJAlNe82Zps3b3bpT23XGXDl5hlOkGDum3vDA";
const GID = "9556364"; // "2026/2" tab
const CSV_URL = `https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=csv&gid=${GID}`;

const CATEGORY_TO_DIVISION: Record<string, DivisionId> = {
  WOMEN: "women",
  PREMIER: "premier",
  "U21 GIRLS": "u21-girls",
  "U21 BOYS": "u21-boys",
};

const teamIdByDivisionAndName = new Map<string, string>();
for (const t of teams)
  teamIdByDivisionAndName.set(`${t.divisionId}::${t.name.trim().toUpperCase()}`, t.id);

function resolveTeamId(divisionId: DivisionId, name: string): string | null {
  return teamIdByDivisionAndName.get(`${divisionId}::${name.trim().toUpperCase()}`) ?? null;
}

async function main() {
  const res = await fetch(CSV_URL);
  if (!res.ok) throw new Error(`Failed to fetch sheet: ${res.status} ${res.statusText}`);
  const csvText = await res.text();
  const rows = parseCsv(csvText);

  const { matches, unresolvedTeams, skippedRows } = parseFixtureRows(rows, {
    seasonYear: SEASON.start.slice(0, 4),
    categoryToDivision: CATEGORY_TO_DIVISION,
    resolveTeamId,
  });

  matches.sort((a, b) => (a.date + a.time).localeCompare(b.date + b.time));

  if (unresolvedTeams.size > 0) {
    console.warn(
      `Warning: ${unresolvedTeams.size} team name(s) in the sheet did not match a known team (kept as text-only, no team link):\n  ` +
        [...unresolvedTeams].join("\n  "),
    );
  }

  if (skippedRows.length > 0) {
    console.warn(
      `Warning: ${skippedRows.length} row(s) in the sheet were skipped entirely (not included as a fixture):\n  ` +
        skippedRows.join("\n  "),
    );
  }

  const outPath = path.join(
    path.dirname(fileURLToPath(import.meta.url)),
    "../src/data/matches.generated.ts",
  );

  const body = JSON.stringify(matches, null, 2);
  const previous = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";

  // The stamp is carried forward whenever the fixtures themselves have not
  // moved, so a run that finds nothing new leaves this file byte-identical and
  // refresh-fixtures.yml's `git diff --quiet` check still short-circuits before
  // committing. A stamp that advanced on every run would commit and redeploy
  // the site every few minutes with no data change behind it.
  const unchanged = previous.includes(`export const matches: Match[] = ${body};`);
  const updatedAt =
    (unchanged ? previous.match(/^export const fixturesUpdatedAt = "([^"]+)";$/m)?.[1] : null) ??
    new Date().toISOString();

  const out = `// AUTO-GENERATED by scripts/refresh-fixtures.ts — do not edit by hand.
// Regenerated from the league Google Sheet. See .github/workflows/refresh-fixtures.yml
import type { Match } from "./types.ts";

// When the fixtures below last CHANGED — not when the sheet was last checked.
// See the stamp logic in scripts/refresh-fixtures.ts for why the distinction
// matters.
export const fixturesUpdatedAt = "${updatedAt}";

export const matches: Match[] = ${body};
`;

  writeFileSync(outPath, out);
  console.log(`Wrote ${matches.length} matches to ${outPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
