/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as LigasRouteImport } from './routes/ligas'
import { Route as TableRouteImport } from './routes/table'
import { Route as LigaSlugRouteImport } from './routes/liga.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const LigasRoute = LigasRouteImport.update({
  id: '/ligas',
  path: '/ligas',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const LigaSlugRoute = LigaSlugRouteImport.update({
  id: '/liga/$slug',
  path: '/liga/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/ligas': typeof LigasRoute
  '/table': typeof TableRoute
  '/liga/$slug': typeof LigaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/ligas': typeof LigasRoute
  '/table': typeof TableRoute
  '/liga/$slug': typeof LigaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/ligas': typeof LigasRoute
  '/table': typeof TableRoute
  '/liga/$slug': typeof LigaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/archive' | '/ligas' | '/table' | '/liga/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/archive' | '/ligas' | '/table' | '/liga/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/archive'
    | '/ligas'
    | '/table'
    | '/liga/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchiveRoute: typeof ArchiveRoute
  LigasRoute: typeof LigasRoute
  TableRoute: typeof TableRoute
  LigaSlugRoute: typeof LigaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ligas': {
      id: '/ligas'
      path: '/ligas'
      fullPath: '/ligas'
      preLoaderRoute: typeof LigasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liga/$slug': {
      id: '/liga/$slug'
      path: '/liga/$slug'
      fullPath: '/liga/$slug'
      preLoaderRoute: typeof LigaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchiveRoute: ArchiveRoute,
  LigasRoute: LigasRoute,
  TableRoute: TableRoute,
  LigaSlugRoute: LigaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
